#!/usr/bin/env python3
import hashlib
import json
import shutil
import wave
from datetime import datetime, timezone
from pathlib import Path

SHARD_DIR = Path("artifacts/cosyvoice-shards")
MANIFEST = Path("data/tts-manifest.json")
LEAD_ALIAS = Path("assets/audio/cosyvoice/latest-lead.wav")
LATEST = Path("data/latest.json")


def clean(value):
    return " ".join(str(value or "").split())


def wav_metadata(path):
    path = Path(path)
    if not path.is_file() or path.stat().st_size < 50000:
        raise RuntimeError(f"missing/invalid F01 WAV: {path}")
    with wave.open(str(path), "rb") as wav:
        if wav.getsampwidth() != 2:
            raise RuntimeError(f"F01 WAV is not PCM16: {path}")
        duration = wav.getnframes() / float(wav.getframerate())
    if duration <= 2:
        raise RuntimeError(f"F01 WAV too short: {path} duration={duration:.3f}")
    return round(duration, 3), path.stat().st_size


def load_previous():
    if not MANIFEST.exists():
        return {}
    try:
        data = json.loads(MANIFEST.read_text(encoding="utf-8"))
        if data.get("engine") != "ASLP-lab/Cosyvoice2-Yue" or data.get("voice") != "F01 female reference":
            return {}
        return data
    except Exception:
        return {}


def previous_by_title(previous):
    out = {}
    for entry in (previous.get("articles") or {}).values():
        title = clean(entry.get("title"))
        if title:
            out[title] = entry
    return out


def main():
    shard_files = sorted(SHARD_DIR.glob("shard-*.json"))
    if not shard_files:
        raise RuntimeError("no CosyVoice shard JSON files found")
    shards = [json.loads(path.read_text(encoding="utf-8")) for path in shard_files]
    first = shards[0]
    expected_key = [
        (item["articleId"], clean(item["title"]), item["contentSha256"])
        for item in first.get("expectedArticles") or []
    ]
    if not expected_key:
        raise RuntimeError("CosyVoice shard has no expectedArticles")

    for shard in shards:
        for field in ("engine", "voice", "language", "date", "leadId", "leadTitle", "sourceSha256", "sourceSetSha256", "collectedStoryCount"):
            if shard.get(field) != first.get(field):
                raise RuntimeError(f"shard metadata mismatch for {field}: {shard.get('shardIndex')}")
        key = [(item["articleId"], clean(item["title"]), item["contentSha256"]) for item in shard.get("expectedArticles") or []]
        if key != expected_key:
            raise RuntimeError(f"expected article set mismatch in shard {shard.get('shardIndex')}")

    if int(first.get("shardCount") or 0) != len(shards):
        raise RuntimeError(f"missing shard artifacts: expected={first.get('shardCount')} found={len(shards)}")
    if int(first.get("collectedStoryCount") or 0) != len(expected_key):
        raise RuntimeError("collectedStoryCount does not match expectedArticles")

    expected = {}
    for article_id, title, digest in expected_key:
        if article_id in expected and expected[article_id]["title"] != title:
            raise RuntimeError(f"article id collision: {article_id}")
        expected[article_id] = {"articleId": article_id, "title": title, "contentSha256": digest}

    generated = {}
    for shard in shards:
        for article_id, raw_entry in (shard.get("entries") or {}).items():
            if article_id in generated:
                raise RuntimeError(f"article generated by multiple shards: {article_id}")
            if article_id not in expected:
                raise RuntimeError(f"unexpected generated article: {article_id}")
            entry = dict(raw_entry)
            if entry.get("contentSha256") != expected[article_id]["contentSha256"]:
                raise RuntimeError(f"generated content hash mismatch: {article_id}")
            artifact_path = Path(str(entry.pop("artifactAudio", "")))
            final_path = Path(str(entry.get("audio") or ""))
            if not artifact_path.is_file():
                raise RuntimeError(f"missing generated shard audio: {artifact_path}")
            final_path.parent.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(artifact_path, final_path)
            duration, size = wav_metadata(final_path)
            entry["durationSeconds"] = duration
            entry["bytes"] = size
            entry["wavEncoding"] = "PCM16"
            generated[article_id] = entry

    previous = load_previous()
    old_titles = previous_by_title(previous)
    latest_sha = hashlib.sha256(LATEST.read_bytes()).hexdigest()
    entries = {}
    generated_count = 0
    reused_count = 0

    for article_id, wanted in expected.items():
        if article_id in generated:
            entries[article_id] = generated[article_id]
            generated_count += 1
            continue

        old = old_titles.get(wanted["title"])
        if old and old.get("contentSha256") == wanted["contentSha256"]:
            path = Path(str(old.get("audio") or ""))
            duration, size = wav_metadata(path)
            entry = dict(old)
            entry.update({
                "articleId": article_id,
                "title": wanted["title"],
                "contentSha256": wanted["contentSha256"],
                "durationSeconds": duration,
                "bytes": size,
                "wavEncoding": "PCM16",
            })
            entries[article_id] = entry
            reused_count += 1
            continue

        if wanted["title"] == clean(first.get("leadTitle")) and previous.get("sourceSha256") == latest_sha and old:
            path = Path(str(old.get("audio") or ""))
            duration, size = wav_metadata(path)
            entry = dict(old)
            entry.update({
                "articleId": article_id,
                "title": wanted["title"],
                "contentSha256": wanted["contentSha256"],
                "durationSeconds": duration,
                "bytes": size,
                "wavEncoding": "PCM16",
            })
            entries[article_id] = entry
            reused_count += 1
            continue

        raise RuntimeError(f"no F01 audio after shard merge: {wanted['title']}")

    if len(entries) != len(expected):
        raise RuntimeError(f"F01 coverage incomplete: {len(entries)}/{len(expected)}")

    lead_title = clean(first.get("leadTitle"))
    lead_entry = next((entry for entry in entries.values() if clean(entry.get("title")) == lead_title), None)
    if not lead_entry:
        raise RuntimeError("lead story missing from merged F01 entries")
    lead_path = Path(lead_entry["audio"])
    LEAD_ALIAS.parent.mkdir(parents=True, exist_ok=True)
    if lead_path.resolve() != LEAD_ALIAS.resolve():
        shutil.copyfile(lead_path, LEAD_ALIAS)
    wav_metadata(LEAD_ALIAS)

    manifest = {
        "version": 2,
        "engine": "ASLP-lab/Cosyvoice2-Yue",
        "voice": "F01 female reference",
        "language": "yue-HK",
        "pronunciationPolicy": "cantonese-only",
        "instructionPolicy": "short-no-leak",
        "coveragePolicy": "all-current-news-f01-only",
        "generationMode": f"parallel-{len(shards)}-shards",
        "generatedAt": datetime.now(timezone.utc).isoformat(),
        "source": "multi-source-current-site",
        "sourceSha256": first["sourceSha256"],
        "sourceSetSha256": first["sourceSetSha256"],
        "sourceFiles": first.get("sourceFiles") or [],
        "date": first.get("date"),
        "leadId": first.get("leadId"),
        "leadTitle": first.get("leadTitle"),
        "articleCount": len(entries),
        "collectedStoryCount": len(expected),
        "generatedArticleCount": generated_count,
        "reusedArticleCount": reused_count,
        "articles": entries,
    }
    MANIFEST.parent.mkdir(parents=True, exist_ok=True)
    MANIFEST.write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(
        f"COSYVOICE_SHARD_MERGE_PASS articles={len(entries)} generated={generated_count} "
        f"reused={reused_count} source_set_sha256={first['sourceSetSha256']}",
        flush=True,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
